### ISSUE TITLE
Code Fixes/TODO's

### ISSUE THREAD

**Issue by Ayilay** [frc-team-3341/cv-2016#2]
So here are some fixes/TODO's that should be fixed by next time:
- Target.cpp:
  - Change line 37 (refuses to compile on some versions of OpenCV apparently)
- TargetProcessor.cpp:
  - Remove ugly comment block towards end of file and fix bracket mismatching (won't compile)
- src/CMakeListst.txt:
  - Last 2 lines, change name of main executable from catapult to cv_2016
  - Change name of main.cpp to cv_2016.cpp
- cv_a2.cpp:
  - Might wanna print units with the measurements
- Remove target.hpp.save from src/

**And please format your code, some of it is hideous :P**

**Comment by trulyronak** [comment]
Fixed all.

**Comment by trulyronak** [comment]
git pull before working to get changes

**Comment by Ayilay** [comment]
Still some issues:
- TargetDetector.cpp still has a hideous comment block in the end, and also the merge conflict footer, please remove it
- cv-2016 should be renamed to cv_2016 in src/CMakeLists.txt
- Remove ALL unnecessary comments, like code that's commented out that will probably never be commented back in. It's distracting and unnecessary, unless it's there for a reason

**Also someone please make some efforts to make the code more readable, code formatting should be taken more seriously among within this project**

**Comment by trulyronak** [comment]
Will try to format the code, removed the code block from TargetDetector.cpp, (that was there for me, sry)

**Comment by trulyronak** [comment]
I didn't push the changes i made, but <a href="http://astyle.sourceforge.net/">astyle</a> did some decent changes, I'll show you later in case you want to go with the changes. You can try them yourself incase you want.
